id: Get File Sample From Path - Generic V2
version: -1
name: Get File Sample From Path - Generic V2
description: |
  This playbook returns a file sample correlating to a path into the War Room using the following sub-playbooks:
  inputs:
  1) Get File Sample From Path - D2.
  2) Get File Sample From Path - VMware Carbon Black EDR (Live Response API).
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5d887731-fb71-4226-872c-a9e8dbddac42
    type: start
    task:
      id: 5d887731-fb71-4226-872c-a9e8dbddac42
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 8adb1ff3-5400-4f88-8a2b-4511ae8303f5
    type: condition
    task:
      id: 8adb1ff3-5400-4f88-8a2b-4511ae8303f5
      version: -1
      name: Use D2 agent?
      description: Yes, if we want to use the D2 agent to get the file.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      - "14"
      "yes":
      - "10"
    scriptarguments:
      left:
        simple: ${inputs.UseD2}
      right:
        simple: "True"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.UseD2
            iscontext: true
          right:
            value:
              simple: "yes"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: f81d6908-8ce9-452b-8dde-689f44256933
    type: title
    task:
      id: f81d6908-8ce9-452b-8dde-689f44256933
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: acf75e5f-0da0-483e-82e2-2dbf09a0362c
    type: playbook
    task:
      id: acf75e5f-0da0-483e-82e2-2dbf09a0362c
      version: -1
      name: Get File Sample From Path - D2
      description: |-
        Returns a file sample to the War Room from a path on an endpoint using Demisto Dissolvable Agent (D2).

        Input:
        * Credentials - credentials to use when trying to deploy Demisto Dissolvable Agent (D2)  (default: Admin)
        * ${Endpoint.Hostname} - deploy agent on target endpoint
        * ${File.Path} - file's path to collect
      playbookName: Get File Sample From Path - D2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Credentials:
        simple: Admin
      Hostname:
        simple: ${inputs.Hostname}
      Path:
        simple: ${inputs.Path}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": -9,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "11":
    id: "11"
    taskid: 906138a1-e3ee-4711-889a-4ebcc8c2a1c6
    type: title
    task:
      id: 906138a1-e3ee-4711-889a-4ebcc8c2a1c6
      version: -1
      name: Use VMware Carbon Black EDR (Live Response API)
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 96e50a4f-9369-4549-885e-7a53814d1548
    type: playbook
    task:
      id: 96e50a4f-9369-4549-885e-7a53814d1548
      version: -1
      name: Get File Sample From Path - VMware Carbon Black EDR - Live Response API
      description: |-
        This playbook retrieves a file from endpoints by path using VMware Carbon Black EDR (Live Response API).
        Make sure to provide the Carbon Black sensor ID of the endpoint from which you want to retrieve the file.
      playbookName: Get File Sample From Path - VMware Carbon Black EDR - Live Response
        API
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Path:
        complex:
          root: inputs.Path
      Sensor_ID:
        complex:
          root: inputs.Agent_ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "13":
    id: "13"
    taskid: dcc8f303-2285-4fcf-8b28-264f6be9f930
    type: playbook
    task:
      id: dcc8f303-2285-4fcf-8b28-264f6be9f930
      version: -1
      name: Cortex XDR - Retrieve File Playbook
      description: |-
        Retrieves files from selected endpoints. You can retrieve up to 20 files, from no more than 10 endpoints.
        Inputs for this playbook are:
        - A comma-separated list of endpoint IDs.
        - A comma-separated list of file paths for your operating system, either Windows, Linux, or Mac. At least one file path is required.
      playbookName: Cortex XDR - Retrieve File Playbook
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      endpoint_ids:
        complex:
          root: inputs.Agent_ID
      linux_file_paths:
        complex:
          root: inputs.LinuxPath
      mac_file_paths:
        complex:
          root: inputs.MacPath
      windows_file_paths:
        complex:
          root: inputs.Path
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 940,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "14":
    id: "14"
    taskid: 4ee35cdb-9c40-4211-8103-a4b7df8d5676
    type: title
    task:
      id: 4ee35cdb-9c40-4211-8103-a4b7df8d5676
      version: -1
      name: Palo Alto Networks Cortex XDR
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 940,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 1329,
        "x": -9,
        "y": 50
      }
    }
  }
inputs:
- key: UseD2
  value: {}
  required: false
  description: |-
    Determines whether a D2 agent will be used to retrieve the file.
    Options:
    no (default)
    yes
  playbookInputQuery:
- key: Hostname
  value: {}
  required: false
  description: Hostname of the machine on which the file is located.
  playbookInputQuery:
- key: Path
  value: {}
  required: false
  description: |
    The path of the file to retrieve.
    For example:
    C:\users\folder\file.txt
  playbookInputQuery:
- key: Agent_ID
  value: {}
  required: false
  description: |-
    The ID of the agent, or of the endpoint, in the relevant integration (such as EDR).
    In Cortex XDR - this should be the Endpoint ID (NOT the hostname). A comma-separated list of Endpoint IDs is supported.
  playbookInputQuery:
- key: LinuxPath
  value: {}
  required: false
  description: The full path of the file in Linux operating systems.
  playbookInputQuery:
- key: MacPath
  value: {}
  required: false
  description: The full path of the file in MacOS systems.
  playbookInputQuery:
outputs:
- contextPath: File.Size
  description: The size of the file.
  type: number
- contextPath: File.Type
  description: The type of the file.
  type: string
- contextPath: File.Info
  description: General information of the file.
  type: string
- contextPath: File.MD5
  description: The MD5 hash of the file.
  type: string
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
  type: string
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
  type: string
- contextPath: File.SHA512
  description: The SHA512 hash of the file.
  type: string
- contextPath: File.EntryID
  description: The file entry ID.
  type: string
- contextPath: File.Extension
  description: The file extension.
  type: string
- contextPath: File.Name
  description: The file name.
  type: string
- contextPath: File.SSDeep
  description: File SSDeep.
  type: string
tests:
- Calculate Severity - Generic v2 - Test
- Test Convert file hash to corresponding hashes
- Detonate URL - Generic Test
- Detonate File - Generic Test
- test-domain-indicator
- Account Enrichment - Generic v2.1 - Test
- Dedup - Generic v2 - Test
- Generic Polling Test
- URL Enrichment - Generic v2 - Test
- Send Investigation Summary Reports - Test
- Endpoint Enrichment - Generic v2.1 - Test
- Wait Until Datetime - Test
- Detonate File - No Files test
- Domain Enrichment - Generic v2 - Test
- Calculate Severity - Standard - Test
- Retrieve File from Endpoint - Generic V2 Test
- Extract Indicators From File - Generic v2 - Test
- Field polling test
- Email Address Enrichment - Generic v2.1 - Test
- File Enrichment - Generic v2 - Test
- IP Enrichment - Generic v2 - Test
fromversion: 5.0.0
