id: OpenCTI_Feed_v2_Test
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: OpenCTI_Feed_v2_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a00ae0a8-cf80-4388-8b9b-153735e3d384
    type: start
    task:
      id: a00ae0a8-cf80-4388-8b9b-153735e3d384
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: fcc41f37-3e16-42c1-852c-5375a9a6ebf5
    type: regular
    task:
      id: fcc41f37-3e16-42c1-852c-5375a9a6ebf5
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 4badbd9a-89ea-4c0e-85bd-767919eac840
    type: regular
    task:
      id: 4badbd9a-89ea-4c0e-85bd-767919eac840
      version: -1
      name: opencti-get-indicators
      script: '|||opencti-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      indicator_types: {}
      last_id: {}
      limit:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 0495ef10-0d1b-4b07-8800-d9d113911259
    type: condition
    task:
      id: 0495ef10-0d1b-4b07-8800-d9d113911259
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicators.type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicators.value
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.LastRunID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 89e3d3d3-c41f-43c8-89b6-9f6e03f8399c
    type: regular
    task:
      id: 89e3d3d3-c41f-43c8-89b6-9f6e03f8399c
      version: -1
      name: opencti-reset-fetch-indicators
      script: '|||opencti-reset-fetch-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 79a1aad2-a397-42ac-81a5-ebc5de525969
    type: regular
    task:
      id: 79a1aad2-a397-42ac-81a5-ebc5de525969
      version: -1
      name: opencti-indicator-delete
      script: '|||opencti-indicator-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: fa441c60-10cd-452a-8e53-5e70be77fb20
    type: regular
    task:
      id: fa441c60-10cd-452a-8e53-5e70be77fb20
      version: -1
      name: opencti-indicator-field-update
      script: '|||opencti-indicator-field-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      key:
        simple: score
      value:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 20c09d54-360a-47fd-8442-3ea3112b912e
    type: condition
    task:
      id: 20c09d54-360a-47fd-8442-3ea3112b912e
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 08d9b2e0-1df3-4ebd-8e16-bfbee12fabb6
    type: regular
    task:
      id: 08d9b2e0-1df3-4ebd-8e16-bfbee12fabb6
      version: -1
      name: opencti-indicator-create-update
      script: '|||opencti-indicator-create-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      created_by: {}
      data:
        simple: '{"value": "BadHost-TestPlaybook"}'
      description:
        simple: Test playbook bad hostname indicator
      external_references_source_name: {}
      external_references_url: {}
      id: {}
      label:
        simple: testplaybook
      marking:
        simple: TLP:GREEN
      score:
        simple: "70"
      type:
        simple: HostName
      update: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: d189002c-5f64-4352-8f90-dc598691ffa4
    type: condition
    task:
      id: d189002c-5f64-4352-8f90-dc598691ffa4
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 0288f0a8-bde4-4f3f-8185-f25a5dc63afa
    type: title
    task:
      id: 0288f0a8-bde4-4f3f-8185-f25a5dc63afa
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 33656dc4-e3f9-44bb-83ec-841704aee58e
    type: regular
    task:
      id: 33656dc4-e3f9-44bb-83ec-841704aee58e
      version: -1
      name: opencti-indicator-marking-remove
      description: Remove marking from indicator.
      script: '|||opencti-indicator-marking-remove'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      marking:
        simple: TLP:GREEN
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 1c69bbe2-6225-48ed-888e-1d582ac8f8c8
    type: regular
    task:
      id: 1c69bbe2-6225-48ed-888e-1d582ac8f8c8
      version: -1
      name: opencti-indicator-label-add
      description: Add labal to indicator.
      script: '|||opencti-indicator-label-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      label:
        simple: test-label
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: e0ca1ff9-8913-4a99-8056-a74bdaa26f7d
    type: regular
    task:
      id: e0ca1ff9-8913-4a99-8056-a74bdaa26f7d
      version: -1
      name: opencti-indicator-label-remove
      description: Remove label from indicator.
      script: '|||opencti-indicator-label-remove'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      label:
        simple: test-label
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 255f0d1e-e047-4c34-8927-acaf61c9597f
    type: regular
    task:
      id: 255f0d1e-e047-4c34-8927-acaf61c9597f
      version: -1
      name: opencti-organization-list
      description: Get list of all organizations.
      script: '|||opencti-organization-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 16fee6e8-823c-472c-83d9-8465db67a161
    type: regular
    task:
      id: 16fee6e8-823c-472c-83d9-8465db67a161
      version: -1
      name: opencti-organization-create
      description: Create organization.
      script: '|||opencti-organization-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      description:
        simple: test playbook organization
      name:
        simple: Test_Organization
      reliability:
        simple: B
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 0836db4e-f029-439f-8b51-86fa5eb05b9c
    type: condition
    task:
      id: 0836db4e-f029-439f-8b51-86fa5eb05b9c
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organizations.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organizations.name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: b4bddecf-a67e-4532-8355-5129d5a30df4
    type: condition
    task:
      id: b4bddecf-a67e-4532-8355-5129d5a30df4
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organization.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3010,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0