id: OpenCTI Feed v2 Test
version: -1
name: OpenCTI Feed v2 Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4a023c69-9bc1-49c9-805d-57740128a304
    type: start
    task:
      id: 4a023c69-9bc1-49c9-805d-57740128a304
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 1dc6c09f-fce5-4131-839a-4759fbcdcf0e
    type: regular
    task:
      id: 1dc6c09f-fce5-4131-839a-4759fbcdcf0e
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: b361bd20-3005-4771-82ad-24684de7f743
    type: regular
    task:
      id: b361bd20-3005-4771-82ad-24684de7f743
      version: -1
      name: opencti-get-indicators
      script: '|||opencti-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      indicator_types: {}
      last_id: {}
      limit:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: bdf45974-da8e-4e0d-8445-e0ae6de3fcfe
    type: condition
    task:
      id: bdf45974-da8e-4e0d-8445-e0ae6de3fcfe
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicators.type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicators.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a5ea583f-3e71-414a-8774-ec957dd5ef74
    type: regular
    task:
      id: a5ea583f-3e71-414a-8774-ec957dd5ef74
      version: -1
      name: opencti-indicator-delete
      script: '|||opencti-indicator-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 762cd836-b4eb-47ef-8ede-859f46fd61a8
    type: regular
    task:
      id: 762cd836-b4eb-47ef-8ede-859f46fd61a8
      version: -1
      name: opencti-indicator-field-update
      script: '|||opencti-indicator-field-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      field:
        simple: score
      value:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 3b5bb1a0-9f7c-40e8-8ef3-5d39ef8dd46b
    type: condition
    task:
      id: 3b5bb1a0-9f7c-40e8-8ef3-5d39ef8dd46b
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 05528c30-91a3-4c10-8c79-25e5f91b576a
    type: regular
    task:
      id: 05528c30-91a3-4c10-8c79-25e5f91b576a
      version: -1
      name: opencti-indicator-create
      description: Create new indicator.
      script: '|||opencti-indicator-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      created_by: {}
      data:
        simple: '{"value": "BadHost-TestPlaybook"}'
      description:
        simple: Test playbook bad hostname indicator
      external_references_source_name: {}
      external_references_url: {}
      label:
        simple: testplaybook
      marking:
        simple: TLP:GREEN
      score:
        simple: "70"
      type:
        simple: HostName
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 42c3b63d-345c-42c8-8604-d77b1e6ee170
    type: condition
    task:
      id: 42c3b63d-345c-42c8-8604-d77b1e6ee170
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.data
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: f5b0e6d9-3b15-4734-8b05-e0271930762a
    type: title
    task:
      id: f5b0e6d9-3b15-4734-8b05-e0271930762a
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: b7a9f5b0-9ff8-4c63-8396-1f5a5c0764e2
    type: regular
    task:
      id: b7a9f5b0-9ff8-4c63-8396-1f5a5c0764e2
      version: -1
      name: opencti-indicator-field-remove
      description: Remove field from indicator. Avalible fields to remove - marking
        defenition, label.
      script: '|||opencti-indicator-field-remove'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      field:
        simple: marking
      value:
        simple: TLP:GREEN
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 041af43b-8fda-473f-87ee-3044fedf5af3
    type: regular
    task:
      id: 041af43b-8fda-473f-87ee-3044fedf5af3
      version: -1
      name: opencti-indicator-field-add
      description: Add field to indicator. Avalible fields to add - marking defenition,
        label.
      script: '|||opencti-indicator-field-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
      field:
        simple: label
      value:
        simple: test1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 4a09d1cb-2661-4ee5-8348-9e0bde0139de
    type: regular
    task:
      id: 4a09d1cb-2661-4ee5-8348-9e0bde0139de
      version: -1
      name: opencti-organization-list
      description: Get list of all organizations.
      script: '|||opencti-organization-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 5fa5387a-4a0b-472b-81b5-6420dbf136b7
    type: regular
    task:
      id: 5fa5387a-4a0b-472b-81b5-6420dbf136b7
      version: -1
      name: opencti-organization-create
      description: Create organization.
      script: '|||opencti-organization-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      description:
        simple: test playbook organization
      name:
        simple: Test_Organization
      reliability:
        simple: B
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 59127e5b-ecec-47e4-8b0e-38ea0d5d5633
    type: condition
    task:
      id: 59127e5b-ecec-47e4-8b0e-38ea0d5d5633
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organizations.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organizations.name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: face2a83-0fbe-45bc-8f98-f4f6dfdf7f82
    type: condition
    task:
      id: face2a83-0fbe-45bc-8f98-f4f6dfdf7f82
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organization.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2660,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0
description: test playbook
