id: OpenCTI Feed v2 Test
version: -1
name: OpenCTI Feed v2 Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 87d2c31b-4e05-4539-8cf1-01e760a7c22d
    type: start
    task:
      id: 87d2c31b-4e05-4539-8cf1-01e760a7c22d
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 5bd76112-d5c8-4120-8f19-a96baa7709ac
    type: regular
    task:
      id: 5bd76112-d5c8-4120-8f19-a96baa7709ac
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 0219b5ad-3582-43df-8778-255479e8d0ec
    type: regular
    task:
      id: 0219b5ad-3582-43df-8778-255479e8d0ec
      version: -1
      name: opencti-get-indicators
      script: '|||opencti-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      indicator_types:
        simple: ALL
      last_id: {}
      limit:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: e900e940-6509-419d-8e51-dd0814cfaef5
    type: condition
    task:
      id: e900e940-6509-419d-8e51-dd0814cfaef5
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicators.type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicators.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: fcdd1a31-0f50-444a-8b64-a3b86112d0d3
    type: regular
    task:
      id: fcdd1a31-0f50-444a-8b64-a3b86112d0d3
      version: -1
      name: opencti-indicator-delete
      script: '|||opencti-indicator-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      id:
        simple: ${OpenCTI.Indicator.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 4220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 95d658b3-1433-4577-87bd-7f5242b27b37
    type: regular
    task:
      id: 95d658b3-1433-4577-87bd-7f5242b27b37
      version: -1
      name: opencti-indicator-field-update
      script: '|||opencti-indicator-field-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      field:
        simple: score
      id:
        simple: ${OpenCTI.Indicator.id}
      value:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: cc34b72c-b5f0-45cd-8537-8b746f9fa4e0
    type: condition
    task:
      id: cc34b72c-b5f0-45cd-8537-8b746f9fa4e0
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 4d3e0af2-551a-4a25-88b9-4bc35dbd34e2
    type: regular
    task:
      id: 4d3e0af2-551a-4a25-88b9-4bc35dbd34e2
      version: -1
      name: opencti-indicator-create
      description: Create new indicator.
      script: '|||opencti-indicator-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      created_by:
        simple: ${OpenCTI.Organization.id}
      data:
        simple: '{"value": "BadHost-TestPlaybook"}'
      description:
        simple: Test playbook bad hostname indicator
      external_references_id: {}
      label:
        simple: testplaybook
      label_id: {}
      marking:
        simple: TLP:GREEN
      marking_id: {}
      score:
        simple: "70"
      type:
        simple: Host
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 59338951-acf8-4e35-822f-184659fcd142
    type: condition
    task:
      id: 59338951-acf8-4e35-822f-184659fcd142
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Indicator.data
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 0e8ee987-8fed-45cc-8f4b-69fb4806eea4
    type: title
    task:
      id: 0e8ee987-8fed-45cc-8f4b-69fb4806eea4
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 4395
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: a7238743-f27e-481b-87ef-84bbdb75a328
    type: regular
    task:
      id: a7238743-f27e-481b-87ef-84bbdb75a328
      version: -1
      name: opencti-indicator-field-remove
      description: Remove field from indicator. Avalible fields to remove - marking
        defenition, label.
      script: '|||opencti-indicator-field-remove'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      field:
        simple: label
      id:
        simple: ${OpenCTI.Indicator.id}
      value:
        simple: ${OpenCTI.Labels.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: cc285b1d-a21f-4613-8dd3-9c694a5d93b7
    type: regular
    task:
      id: cc285b1d-a21f-4613-8dd3-9c694a5d93b7
      version: -1
      name: opencti-indicator-field-add
      description: Add field to indicator. Avalible fields to add - marking defenition,
        label.
      script: '|||opencti-indicator-field-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      field:
        simple: label
      id:
        simple: ${OpenCTI.Indicator.id}
      value:
        simple: ${OpenCTI.Labels.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 57b560ff-96fd-4fbe-8b24-685a9fa0a794
    type: regular
    task:
      id: 57b560ff-96fd-4fbe-8b24-685a9fa0a794
      version: -1
      name: opencti-organization-list
      description: Get list of all organizations.
      script: '|||opencti-organization-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 38f1495e-6fbb-436c-8d41-282dc673f4b0
    type: regular
    task:
      id: 38f1495e-6fbb-436c-8d41-282dc673f4b0
      version: -1
      name: opencti-organization-create
      description: Create organization.
      script: '|||opencti-organization-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      description:
        simple: test playbook organization
      name:
        simple: Test_Organization
      reliability:
        simple: B
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 10d0ba82-a271-4ef3-8a62-ad043d699ec2
    type: condition
    task:
      id: 10d0ba82-a271-4ef3-8a62-ad043d699ec2
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organizations.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organizations.name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 4045
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 4aa1b83d-e160-4725-85d0-7d8c45721cf1
    type: condition
    task:
      id: 4aa1b83d-e160-4725-85d0-7d8c45721cf1
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Organization.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "18":
    id: "18"
    taskid: 2c7f57a2-edbc-4a98-8df1-ced8c8eafed6
    type: regular
    task:
      id: 2c7f57a2-edbc-4a98-8df1-ced8c8eafed6
      version: -1
      name: opencti-label-list
      description: Get list of all labels.
      script: '|||opencti-label-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      last_run_id: {}
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "19":
    id: "19"
    taskid: 7293befe-1623-45b8-8e7b-671f901b5eb7
    type: condition
    task:
      id: 7293befe-1623-45b8-8e7b-671f901b5eb7
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "20"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Labels.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Labels.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "20":
    id: "20"
    taskid: 676d03b8-481e-4a35-8b1d-3d22ec020d69
    type: regular
    task:
      id: 676d03b8-481e-4a35-8b1d-3d22ec020d69
      version: -1
      name: opencti-marking-definition-list
      description: Get list of all marking definitions.
      script: '|||opencti-marking-definition-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      last_run_id: {}
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "21":
    id: "21"
    taskid: ad47992d-1b50-4784-86f3-19560780e825
    type: condition
    task:
      id: ad47992d-1b50-4784-86f3-19560780e825
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.MarkingDefinitions.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.MarkingDefinitions.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "22":
    id: "22"
    taskid: 61202b64-6d2e-43cf-80fa-bb6cd54a1ec9
    type: regular
    task:
      id: 61202b64-6d2e-43cf-80fa-bb6cd54a1ec9
      version: -1
      name: opencti-external-reference-create
      description: Create external reference.
      script: '|||opencti-external-reference-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      source_name:
        simple: TestPlaybook
      url:
        simple: www.testplaybook.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "23":
    id: "23"
    taskid: 9bdb058d-b387-4909-8de7-a38abeb38729
    type: condition
    task:
      id: 9bdb058d-b387-4909-8de7-a38abeb38729
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "24"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.externalReference.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "24":
    id: "24"
    taskid: d6bc37d0-9816-4622-8fa3-6d86e713c3b1
    type: regular
    task:
      id: d6bc37d0-9816-4622-8fa3-6d86e713c3b1
      version: -1
      name: opencti-marking-definition-create
      description: Create marking definition.
      script: '|||opencti-marking-definition-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      name:
        simple: TLP:RED
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "25":
    id: "25"
    taskid: 3245e069-78e1-4885-804d-373334d13fd7
    type: condition
    task:
      id: 3245e069-78e1-4885-804d-373334d13fd7
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "26"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.MarkingDefinition.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3345
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "26":
    id: "26"
    taskid: b83ea59f-915e-4dba-81e5-2f0a1d7fe4bb
    type: regular
    task:
      id: b83ea59f-915e-4dba-81e5-2f0a1d7fe4bb
      version: -1
      name: opencti-label-create
      description: Create label.
      script: '|||opencti-label-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      name:
        simple: testplaybook
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "27":
    id: "27"
    taskid: e7e8270b-12b3-4fbf-8a51-eb7baa4ecf80
    type: condition
    task:
      id: e7e8270b-12b3-4fbf-8a51-eb7baa4ecf80
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: OpenCTI.Label.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3695
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 4410,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0
description: test playbook
